<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>io.github.dbstarll.parent</groupId>
    <artifactId>base</artifactId>
    <version>1.4.0-SNAPSHOT</version>
    <relativePath>../base</relativePath>
  </parent>
  <artifactId>boot</artifactId>
  <packaging>pom</packaging>

  <name>boot</name>
  <description>parent for spring boot</description>
  <url>https://github.com/dbstar-org/parent/tree/main/boot</url>

  <scm>
    <url>${project.git.web.master}</url>
    <connection>scm:git:${project.git.git.root}</connection>
    <developerConnection>scm:git:${project.git.web.root}</developerConnection>
    <tag>HEAD</tag>
  </scm>

  <properties>
    <project.spring-boot.attach>false</project.spring-boot.attach>
    <project.spring-boot.classifier>boot</project.spring-boot.classifier>
    <version.spring-boot>2.7.18</version.spring-boot>
    <version.git-commit-id-plugin>4.9.10</version.git-commit-id-plugin>
  </properties>

  <profiles>
    <profile>
      <id>spring-boot</id>
      <activation>
        <file>
          <exists>src/main/java</exists>
        </file>
      </activation>
      <build>
        <filters>
          <filter>target/classes/git.properties</filter>
        </filters>
        <pluginManagement>
          <plugins>
            <plugin>
              <groupId>pl.project13.maven</groupId>
              <artifactId>git-commit-id-plugin</artifactId>
              <version>${version.git-commit-id-plugin}</version>
              <executions>
                <execution>
                  <goals>
                    <goal>revision</goal>
                  </goals>
                </execution>
              </executions>
              <configuration>
                <generateGitPropertiesFile>true</generateGitPropertiesFile>
                <includeOnlyProperties>
                  <includeOnlyProperty>git.commit.id</includeOnlyProperty>
                  <includeOnlyProperty>git.commit.id.describe</includeOnlyProperty>
                  <includeOnlyProperty>git.commit.time</includeOnlyProperty>
                </includeOnlyProperties>
              </configuration>
            </plugin>
            <plugin>
              <groupId>org.springframework.boot</groupId>
              <artifactId>spring-boot-maven-plugin</artifactId>
              <version>${version.spring-boot}</version>
              <configuration>
                <attach>${project.spring-boot.attach}</attach>
                <classifier>${project.spring-boot.classifier}</classifier>
                <!--suppress UnresolvedMavenProperty -->
                <mainClass>${project.mainClass}</mainClass>
              </configuration>
              <executions>
                <execution>
                  <goals>
                    <goal>repackage</goal>
                  </goals>
                </execution>
              </executions>
            </plugin>
          </plugins>
        </pluginManagement>
        <plugins>
          <plugin>
            <groupId>pl.project13.maven</groupId>
            <artifactId>git-commit-id-plugin</artifactId>
          </plugin>
          <plugin>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-maven-plugin</artifactId>
          </plugin>
        </plugins>
      </build>
    </profile>
  </profiles>
</project>
