name: deploy-release

on:
  pull_request:
    branches:
      - release
      - release-*

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Generate Maven Settings
        uses: whelk-io/maven-settings-xml-action@v18
        with:
          servers: >
            [
              {
                "id": "github",
                "username": "${env.GITHUB_ACTOR}",
                "password": "${{ secrets.GITHUB_TOKEN }}"
              },
              {
                "id": "ossrh",
                "username": "${{ secrets.OSS_USERNAME }}",
                "password": "${{ secrets.OSS_PASSWORD }}"
              }
            ]

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots clean verify -P repository-ossrh,repository-github

      - name: Deploy with Maven
        run: mvn --batch-mode --update-snapshots clean deploy -P release,repository-ossrh,distribution-ossrh,repository-github,distribution-github