name: verify

on:
  push:
    branches-ignore:
      - release
      - release-*
      - main
      - snapshot-*
  pull_request:
    branches-ignore:
      - release
      - release-*
      - main
      - snapshot-*
  workflow_dispatch:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots clean verify -P repository-ossrh